include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "lightsoff-dev.flatpak"

flatpak:
    variables:
        MANIFEST_PATH: "build-aux/org.gnome.LightsOff.json"
        FLATPAK_MODULE: "lightsoff"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.LightsOff"
    extends: .flatpak

nightly:
    extends: '.publish_nightly'
    # assuming your job in named 'flatpak'
    dependencies: ['flatpak']
    needs: ['flatpak']
