name: lightsoff
version: 3.30.0
summary: Turn off all the lights
description: |
  Lights Off is a collection of light switch puzzles. Clicking on a light
  toggles it either on or off, but also toggles all the surrounding lights,
  too. Your objective is simple: turn off all the lights!

  Players who delight in turning off lights will enjoy the huge number of
  levels.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
    gnome-3-26-1604:
      interface: content
      target: $SNAP/gnome-platform
      default-provider: gnome-3-26-1604

slots:
  # for GtkApplication registration
  lightsoff:
    interface: dbus
    bus: session
    name: org.gnome.lightsoff

apps:
  lightsoff:
    command: desktop-launch lightsoff
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - pulseaudio
      - opengl
      - unity7
      - wayland
    desktop: usr/share/applications/lightsoff.desktop
    environment:
      PATH: $SNAP/usr/games:$PATH

parts:
  lightsoff:
    build-attributes: [no-system-libraries]
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    source-tag: 3.30.0
    override-build: |
      sed -i.bak -e 's|Icon=lightsoff$|Icon=${SNAP}/meta/gui/lightsoff.svg|g' data/lightsoff.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/apps/lightsoff.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/lightsoff/current/usr/share/applications/lightsoff.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/lightsoff/current/usr, --bindir=/snap/lightsoff/current/usr/games]
    organize:
      snap/lightsoff/current/usr: usr
    build-packages:
      - itstool
      - libclutter-gtk-1.0-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - librsvg2-dev
      - valac
    stage-packages:
      - libclutter-gtk-1.0-0
